theme: jekyll-theme-cayman
title: ZERO Bolg
SEOTitle: ZERO Bolg
header-img: img/home-bg-hill.jpg

description: "人工智能"
keyword: "AI、Deep-learning、Machine-learning"
url: "https://AIZERO.github.io"
baseurl: ""
author : ZERO
#name :
email: zero@osai.club
github : AIZERO
#twitter : username
#feedburner : feedname