theme: jekyll-theme-cayman
title: ZERO Bolg
SEOTitle: ERO Bolg
header-img: img/home-bg-hill.jpg
email: zero@osai.club
description: "这个是一个博客"
keyword: "AI、Deep-learning、Machine-learning"
url: "https://AIZERO.github.io"
baseurl: ""
