theme: jekyll-theme-cayman
title: ZERO Blog
SEOTitle: ZERO Blog
header-img: "img/post-bg-js-module.jpg"

description: "人工智能"
keyword: "AI、Deep-learning、Machine-learning"
url: "https://AIZERO.github.io"
baseurl: ""
author : ZERO
#name :
email: zero@osai.club
github : AIZERO
#twitter : username
#feedburner : feedname
rouge: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
      header-img: "img/home-bg-o.jpg" # We don't want posts without a header image, that whould mean white on white